"""Language-neutral orchestration for the Shit Mountain Index."""

from __future__ import annotations

import difflib
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, Sequence

README_START = "<!-- SMI:START -->"
README_END = "<!-- SMI:END -->"


@dataclass(frozen=True)
class ExhibitSpec:
    exhibit_id: str
    slug: str
    sources: tuple[Path, ...]


class Adapter(Protocol):
    language: str
    display_name: str
    extensions: tuple[str, ...]

    def legacy_exhibits(self, root: Path) -> Sequence[ExhibitSpec]: ...

    def analyze_sources(self, sources: Sequence[Path]) -> dict[str, int]: ...


@dataclass(frozen=True)
class Exhibit:
    exhibit_id: str
    slug: str
    language: str
    display_language: str
    sources: tuple[Path, ...]
    adapter: Adapter


@dataclass(frozen=True)
class Result:
    exhibit: Exhibit
    components: dict[str, int]
    score: int
    level: str


def danger_level(score: int) -> str:
    if score <= 20:
        return "轻微异味，可步行参观"
    if score <= 50:
        return "建议佩戴防护设备"
    if score <= 80:
        return "铲屎车进入一级战备"
    return "建议原地成立事故调查组"


def _split_exhibit_name(name: str) -> tuple[str, str]:
    if "-" not in name:
        return "???", name
    return tuple(name.split("-", 1))  # type: ignore[return-value]


def discover_exhibits(root: Path, adapters: Sequence[Adapter]) -> list[Exhibit]:
    exhibits: list[Exhibit] = []

    for adapter in sorted(adapters, key=lambda item: item.language):
        for spec in adapter.legacy_exhibits(root):
            exhibits.append(
                Exhibit(
                    exhibit_id=spec.exhibit_id,
                    slug=spec.slug,
                    language=adapter.language,
                    display_language=adapter.display_name,
                    sources=spec.sources,
                    adapter=adapter,
                )
            )

        language_root = root / "exhibits" / adapter.language
        for bad_directory in sorted(language_root.glob("*/bad")):
            exhibit_id, slug = _split_exhibit_name(bad_directory.parent.name)
            sources = tuple(
                sorted(
                    {
                        source
                        for extension in adapter.extensions
                        for source in bad_directory.rglob(f"*{extension}")
                    }
                )
            )
            if not sources:
                continue
            exhibits.append(
                Exhibit(
                    exhibit_id=exhibit_id,
                    slug=slug,
                    language=adapter.language,
                    display_language=adapter.display_name,
                    sources=sources,
                    adapter=adapter,
                )
            )

    return sorted(
        exhibits,
        key=lambda item: (item.exhibit_id, item.language, item.slug),
    )


def analyze_exhibit(exhibit: Exhibit) -> Result:
    components = exhibit.adapter.analyze_sources(exhibit.sources)
    if any(value < 0 for value in components.values()):
        raise ValueError(f"negative SMI component for {exhibit.slug}")
    score = min(sum(components.values()), 100)
    return Result(
        exhibit=exhibit,
        components=components,
        score=score,
        level=danger_level(score),
    )


def analyze_all(root: Path, adapters: Sequence[Adapter]) -> list[Result]:
    return [analyze_exhibit(exhibit) for exhibit in discover_exhibits(root, adapters)]


def top_contributors(components: dict[str, int], limit: int = 3) -> str:
    ranked = sorted(
        ((name, value) for name, value in components.items() if value),
        key=lambda item: (-item[1], item[0]),
    )
    if not ranked:
        return "未检测到显著异味"
    return " / ".join(f"{name} {value}" for name, value in ranked[:limit])


def render_leaderboard(results: Sequence[Result]) -> str:
    ranked = sorted(
        results,
        key=lambda result: (
            -result.score,
            result.exhibit.exhibit_id,
            result.exhibit.language,
            result.exhibit.slug,
        ),
    )
    lines = [
        README_START,
        "<!-- Generated by scripts/smi.py. Manual edits inside this block will be overwritten. -->",
        "",
        "### 当前排行榜",
        "",
        "| 排名 | 编号 | 展品 | 语言 | SMI | 景区判定 | 主要贡献 |",
        "|---:|---:|---|---|---:|---|---|",
    ]
    for position, result in enumerate(ranked, start=1):
        lines.append(
            f"| {position} | `{result.exhibit.exhibit_id}` | "
            f"`{result.exhibit.slug}` | {result.exhibit.display_language} | "
            f"**{result.score}** | {result.level} | "
            f"{top_contributors(result.components)} |"
        )

    lines.extend(
        [
            "",
            "> SMI 仅用于教育、娱乐和代码审查训练，不用于评价开发者能力或工作绩效。",
            README_END,
        ]
    )
    return "\n".join(lines)


def replace_generated_section(readme: str, generated: str) -> str:
    if README_START not in readme or README_END not in readme:
        raise ValueError(
            f"README must contain both {README_START!r} and {README_END!r}"
        )
    start = readme.index(README_START)
    end = readme.index(README_END, start) + len(README_END)
    return readme[:start] + generated + readme[end:]


def expected_readme(root: Path, adapters: Sequence[Adapter]) -> str:
    readme_path = root / "README.md"
    current = readme_path.read_text(encoding="utf-8")
    return replace_generated_section(current, render_leaderboard(analyze_all(root, adapters)))


def write_readme(root: Path, adapters: Sequence[Adapter]) -> None:
    readme_path = root / "README.md"
    readme_path.write_text(expected_readme(root, adapters), encoding="utf-8")
    print(f"[smi] updated {readme_path.relative_to(root)}")


def check_readme(root: Path, adapters: Sequence[Adapter]) -> int:
    readme_path = root / "README.md"
    current = readme_path.read_text(encoding="utf-8")
    expected = expected_readme(root, adapters)
    if current == expected:
        print("[smi] leaderboard is current")
        return 0

    print("[smi] README leaderboard is stale; run: python3 scripts/smi.py --write")
    difference = difflib.unified_diff(
        current.splitlines(),
        expected.splitlines(),
        fromfile="README.md",
        tofile="README.md (generated)",
        lineterm="",
    )
    print("\n".join(difference))
    return 1
